### ISSUE TITLE
Directly navigating to http://localhost:3000/hymn while logged out redirects to http://localhost:3000/sign-in

### ISSUE THREAD

**Issue by readeral** [Vision100IT/pwad.org.au#30]
I don't think we use /sign-in anymore? clicking log in with google on /sign-in goes to http://localhost:3000/auth/google? which fails to load anything.

**Comment by BarryThePenguin** [comment]
Ya, either..

- needs to go to `/api/login` instead
- or we make `/sign-in` work with `auth0`
