### ISSUE TITLE
Import existing users into sanity/auth0

### ISSUE THREAD

**Issue by readeral** [Vision100IT/pwad.org.au#41]
The list of users has been emailed to support@ containing name and email

**Comment by readeral** [comment]
Users have been created in auth0 - still need to import into sanity

**Comment by BarryThePenguin** [comment]
They'll import to Sanity as people log in

**Comment by readeral** [comment]
I guess so. Is there some mechanism in auth0 to tell them to set a new password? Or I guess they’ll be emailed about it

**Comment by BarryThePenguin** [comment]
We'll have to let them know, that when they log in next time, they'll need to reset their password. Or use their google account to login

**Comment by readeral** [comment]
So we can close this as wontfix?
