### ISSUE TITLE
Auth0 doesn't prompt for First/Last name when signing up

### ISSUE THREAD

**Issue by readeral** [Vision100IT/pwad.org.au#43]
Signing up with a non-gmail email results in no name values being added to the database:

![image](https://user-images.githubusercontent.com/15904136/74003229-f968c780-49c5-11ea-818f-d8c129498f34.png)
![image](https://user-images.githubusercontent.com/15904136/74003234-fec61200-49c5-11ea-84fc-99ca2d2bfa55.png)

**Comment by BarryThePenguin** [comment]
If you logout, and try creating the account again, the details should come through now

**Comment by readeral** [comment]
Excellent
